from math import sqrt
from config import radius, shelf_center


x0, y0 = shelf_center
delta_x = radius/2
delta_y = radius/4

DX = 2*radius + delta_x
DY = 4*radius/sqrt(3) - delta_y
DS = radius + delta_x/2

shelf_coords = {"А1": (x0 - 4*DX - DS, y0 + 3*DY),
                "А2": (x0 - 3*DX - DS, y0 + 3*DY),
                "А3": (x0 - 2*DX - DS, y0 + 3*DY),
                "А4": (x0 - DX - DS, y0 + 3*DY),
                "А5": (x0 - DS, y0 + 3*DY),
                "А6": (x0 + DS, y0 + 3*DY),
                "А7": (x0 + DX + DS , y0 + 3*DY),
                "А8": (x0 + 2*DX + DS, y0 + 3*DY),
                "А9": (x0 + 3*DX + DS, y0 + 3*DY),
                "А10": (x0 + 4*DX + DS, y0 + 3*DY),
                "Б1": (x0 - 4*DX, y0 + 2*DY),
                "Б2": (x0 - 3*DX, y0 + 2*DY),
                "Б3": (x0 - 2*DX, y0 + 2*DY),
                "Б4": (x0 - DX, y0 + 2*DY),
                "Б5": (x0, y0 + 2*DY),
                "Б6": (x0 + DX, y0 + 2*DY),
                "Б7": (x0 + 2*DX, y0 + 2*DY),
                "Б8": (x0 + 3*DX, y0 + 2*DY),
                "Б9": (x0 + 4*DX, y0 + 2*DY),
                "В1": (x0 - 4 * DX - DS, y0 + DY),
                "В2": (x0 - 3 * DX - DS, y0 + DY),
                "В3": (x0 - 2 * DX - DS, y0 + DY),
                "В4": (x0 - DX - DS, y0 + DY),
                "В5": (x0 - DS, y0 + DY),
                "В6": (x0 + DS, y0 + DY),
                "В7": (x0 + DX + DS, y0 + DY),
                "В8": (x0 + 2 * DX + DS, y0 + DY),
                "В9": (x0 + 3 * DX + DS, y0 + DY),
                "В10": (x0 + 4 * DX + DS, y0 + DY),
                "Г1": (x0 - 4*DX, y0),
                "Г2": (x0 - 3*DX, y0),
                "Г3": (x0 - 2*DX, y0),
                "Г4": (x0 - DX, y0),
                "Г5": (x0, y0),
                "Г6": (x0 + DX, y0),
                "Г7": (x0 + 2*DX, y0),
                "Г8": (x0 + 3*DX, y0),
                "Г9": (x0 + 4*DX, y0),
                "Д1": (x0 - 4 * DX - DS, y0 - DY),
                "Д2": (x0 - 3 * DX - DS, y0 - DY),
                "Д3": (x0 - 2 * DX - DS, y0 - DY),
                "Д4": (x0 - DX - DS, y0 - DY),
                "Д5": (x0 - DS, y0 - DY),
                "Д6": (x0 + DS, y0 - DY),
                "Д7": (x0 + DX + DS, y0 - DY),
                "Д8": (x0 + 2 * DX + DS, y0 - DY),
                "Д9": (x0 + 3 * DX + DS, y0 - DY),
                "Д10": (x0 + 4 * DX + DS, y0 - DY),
                "Е1": (x0 - 4*DX, y0 - 2*DY),
                "Е2": (x0 - 3*DX, y0 - 2*DY),
                "Е3": (x0 - 2*DX, y0 - 2*DY),
                "Е4": (x0 - DX, y0 - 2*DY),
                "Е5": (x0, y0 - 2*DY),
                "Е6": (x0 + DX, y0 - 2*DY),
                "Е7": (x0 + 2*DX, y0 - 2*DY),
                "Е8": (x0 + 3*DX, y0 - 2*DY),
                "Е9": (x0 + 4*DX, y0 - 2*DY),
                "Ж1": (x0 - 4 * DX - DS, y0 - 3*DY),
                "Ж2": (x0 - 3 * DX - DS, y0 - 3*DY),
                "Ж3": (x0 - 2 * DX - DS, y0 - 3*DY),
                "Ж4": (x0 - DX - DS, y0 - 3*DY),
                "Ж5": (x0 - DS, y0 - 3*DY),
                "Ж6": (x0 + DS, y0 - 3*DY),
                "Ж7": (x0 + DX + DS, y0 - 3*DY),
                "Ж8": (x0 + 2 * DX + DS, y0 - 3*DY),
                "Ж9": (x0 + 3 * DX + DS, y0 - 3*DY),
                "Ж10": (x0 + 4 * DX + DS, y0 - 3*DY)}

